name: CI
on:
  pull_request:
    branches: ["main"]
    types: ["opened", "reopened", "edited", "synchronize"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-node
      - name: Check formatting
        run: pnpm fmt
      - name: Check linting
        run: pnpm lint
